version: '3.9'
services:
  crm-nginx:
    image: nginx:1.19.7
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/cert:/etc/nginx/cert
